# Generated by Django 2.2.17 on 2020-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
